
Bindings = {
  bus = {},
  panel = {
    "Ctrl-Space Space       Enter into CPU debug mode after complete reset",
    "Ctrl-Space a           Enter into CPU debug at current point",
    "Ctrl-Space d           Leave from CPU debug mode",
    "Ctrl-Space z           Open selected window to the full screen",
    "Ctrl-Space ?           Open selected window bindings",
    "Ctrl-Space &           Gracufully close the PROGRAM",
    "Ctrl-Space :           Prompt for a command",
    "Ctrl-Space q <digit>   Move to the window by number",
    "Ctrl-Space w <digit>   Move to the editor tab by number",
  },
  memory = {
    "C                      Enter into CHARACTER mode",
    "x                      Reset value in this memory address",
    "y y                    Copy value from this memory address",
    "e                      Move cursor back to one address", 
    "a                      Enter into INSERT mode at the next address",
    "c                      Change value in this memory address",
    "0                      Move to the first address by X in current line",
    "$                      Move to the last address by X in current line",
    "g g                    Move to the address 0",
    "G                      Move to the last address in memory",
    "G                      Move to the last address in memory",
    "D                      Enter into DISASSEMBLE mode",
    "i                      Insert value with shift", 
    "g d                    Find defenition in asm code", 
    ";                      Find the next closest search value", 
    ",                      Find the prev closest search value", 
    "f                      Find the value before cursor", 
    "F                      Find the value after cursor", 
    "n                      Find the next closest word", 
    "N                      Find the next closest word", 
    "/                      Find the word before cursor", 
    "?                      Find the word after cursor", 
    "P                      Past the value with shift after cursor", 
    "p                      Past the value with shift before cursor", 
    "d d                    Delete current memory bank with shift",
    "y <i j k l>            Copy values into the buffer",
    "d <i j k l>            Delete values with shift",
    "w                      Go the next memory bank",
    "b                      Go the prev memory bank",
    "Ctrl-u                 Jump the next page in memory",
    "Ctrl-d                 Jump the prev page in memory",
    "Ctrl-d                 Jump the prev page in memory",
    "j                      Go to the upper memory bank",
    "k                      Go to the downer memory bank",
    "l                      Go the next memory bank",
    "h                      Go the prev memory bank",
  },
  editor = {
    "HELLO WORLD",
  },
  popup = {},
}