
Bindings = {
  bus = {},
  panel = {
    "Ctrl-Space Space       Enter into CPU debug mode after complete reset",
    "Ctrl-Space a           Enter into CPU debug at current point",
    "Ctrl-Space d           Leave from CPU debug mode",
    "Ctrl-Space z           Open selected window to the full screen",
    "Ctrl-Space ?           Open selected window bindings",
    "Ctrl-Space &           Gracufully close the PROGRAM",
    "Ctrl-Space :           Prompt for a command",
    "Ctrl-Space q <digit>   Move to the window by number",
    "Ctrl-Space w <digit>   Move to the editor tab by number",
  },
  memory = {
    "C                      Enter into CHARACTER mode",
    "x                      Reset value in this memory address",
    "y y                    Copy value from this memory address",
    "e                      Move cursor back to one address", 
    "a                      Enter into INSERT mode at the next address",
    "c                      Change value in this memory address",
    "0                      Move to the first address by X in current line",
    "$                      Move to the last address by X in current line",
    "g g                    Move to the address 0",
    "G                      Move to the last address in memory",
    "G                      Move to the last address in memory",
    "D                      Enter into DISASSEMBLE mode",
    "i                      Insert value with shift", 
    "g d                    Find defenition in asm code", 
    ";                      Find the next closest search value", 
    ",                      Find the prev closest search value", 
    "f                      Find the value before cursor", 
    "F                      Find the value after cursor", 
    "n                      Find the next closest word", 
    "N                      Find the next closest word", 
    "/                      Find the word before cursor", 
    "?                      Find the word after cursor", 
    "P                      Past the value with shift after cursor", 
    "p                      Past the value with shift before cursor", 
    "d d                    Delete current memory bank with shift",
    "y <i j k l>            Copy values into the buffer",
    "d <i j k l>            Delete values with shift",
    "w                      Go the next memory bank",
    "b                      Go the prev memory bank",
    "Ctrl-u                 Jump the next page in memory",
    "Ctrl-d                 Jump the prev page in memory",
    "Ctrl-d                 Jump the prev page in memory",
    "j                      Go to the upper memory bank",
    "k                      Go to the downer memory bank",
    "l                      Go the next memory bank",
    "h                      Go the prev memory bank",
  },
  editor = {
    "i                      Enter INSERT mode at cursor position",
    "v                      Enter VISUAL mode to select text",
    "y y                    Copy current line",
    "d d                    Delete current line",
    "c c                    Change current line",
    "x                      Delete character under the cursor",
    "u                      Undo last action",
    "Ctrl-r                 Redo last undone action",
    "a                      Enter INSERT mode after the cursor",
    "o                      Open new line below and enter INSERT mode",
    "O                      Open new line above and enter INSERT mode",
    "0                      Move to the beginning of the line",
    "$                      Move to the end of the line",
    "g g                    Move to the beginning of the file",
    "G                      Move to the end of the file",
    "d w                    Delete word",
    "y w                    Copy word",
    "p                      Paste after cursor",
    "P                      Paste before cursor",
    "/                      Start forward search",
    "?                      Start backward search",
    "n                      Repeat search forward",
    "N                      Repeat search backward",
    ";                      Repeat last 'f', 't', 'F', or 'T' search forward",
    ",                      Repeat last 'f', 't', 'F', or 'T' search backward",
    "f [char]               Find next occurrence of [char] in line",
    "F [char]               Find previous occurrence of [char] in line",
    "w                      Move to the beginning of the next word",
    "b                      Move to the beginning of the previous word",
    "e                      Move to the end of the next word",
    "Ctrl-u                 Scroll up half a page",
    "Ctrl-d                 Scroll down half a page",
    "j                      Move cursor down one line",
    "k                      Move cursor up one line",
    "h                      Move cursor left",
    "l                      Move cursor right",
  },
  popup = {},
}