; Variables name
STACK          EQU 0x5FFF
LED_PORT       EQU 0x00
HEX_PORT       EQU 0x10
PPI_PORT_A     EQU 0x20
PPI_PORT_B     EQU 0x21
PPI_PORT_C     EQU 0x22

LCD_IO_EN      EQU 0x03
LCD_IO_CMD     EQU 0x01



LCD_CLEAR      EQU 0x01
LCD_RETURN     EQU 0x02
LCD_MODE       EQU 0x04
LCD_DISPLAY    EQU 0x08
LCD_CURSOR     EQU 0x10
LCD_FUNCTION   EQU 0x20
LCD_CGRAM      EQU 0x40
LCD_DDRAM      EQU 0x80

LCD_CURSOR_LEFT  EQU 0x10
LCD_CURSOR_RIGHT EQU 0x14

MOUNT_DI       EQU 0x00
MOUNT_EN       EQU 0x01



;; Static FUNC ptr
PTR_ADDR           EQU 0x4000
PTR_LCD_MODE       EQU PTR_ADDR + 1
PTR_LCD_DISPLAY    EQU PTR_ADDR + 2
PTR_LCD_CURSOR     EQU PTR_ADDR + 3
PTR_PRINTF_RET     EQU PTR_ADDR + 4
PTR_PREV_SCAN_CODE EQU PTR_ADDR + 5
PTR_TEXT_BUFF_BGN  EQU PTR_ADDR + 6
PTR_TEXT_BUFF_END  EQU PTR_ADDR + 7

; Dynamic args
PTR_FUNC_ARGS      EQU PTR_ADDR + 6


;; Allocated memory
SCAN_KEY_BUF       EQU 0x40F0  ;; F0h - FFh Keybuffer
SCAN_KEY_MAP       EQU 0x4100  ;; 00h - FFh scan codes
TEXT_BUF_MAP       EQU 0x4200  ;; 00h - FFh text buffer
SUPER_BLOCK_MAP    EQU 0x4300  ;; 00h - 1Fh Super block map
INODE_MAP          EQU 0x4320  ;; 20h - FFh Inode map
DATA_ZONE_MAP      EQU 0x4400  ;; 00h - FFh Data zone map


;; Keys alias
KEY_SHIFT          EQU SCAN_KEY_MAP | 0x12

#include "ASCII.asm"